### ISSUE TITLE
Server crashes when using http2 on Windows

### ISSUE THREAD

**Issue by bennypowers** [lwsjs/local-web-server#87] opened 2018-03-04 19:23 UTC
```js
// lws.config.js
module.exports = {
  stack: [
    'lws-body-parser',
    'lws-request-monitor',
    'lws-log',
    'lws-compress',
    'lws-mock-response',
    'lws-static',
    'lws-cors',
  ],
  server: 'http2',
  mocks: './restaurant-mocks.js',
  logFormat: 'stats'
};
```

```
$ npm start

> mws-restaurant-stage-1@1.0.0 start C:\Users\bennyp\My Documents\mws-restaurant-stage-1
> node -v && npx ws --verbose

v9.5.0
npx: installed 1 in 2.862s
Path must be a string. Received undefined
C:\Users\bennyp\My Documents\mws-restaurant-stage-1\node_modules\local-web-server\bin\cli.js
TypeError: loadModule(...) is not a function
    at Lws.createServer (C:\Users\bennyp\Documents\mws-restaurant-stage-1\node_modules\lws\lib\lws.js:126:58)
    at Lws.listen (C:\Users\bennyp\Documents\mws-restaurant-stage-1\node_modules\lws\lib\lws.js:47:25)
    at WsServe.execute (C:\Users\bennyp\Documents\mws-restaurant-stage-1\node_modules\lws\lib\command\serve.js:280:26)
    at WsServe.execute (C:\Users\bennyp\Documents\mws-restaurant-stage-1\node_modules\local-web-server\lib\command\serve.js:16:18)
    at Map.start (C:\Users\bennyp\Documents\mws-restaurant-stage-1\node_modules\cli-commands\index.js:26:18)
    at WsCliApp.start (C:\Users\bennyp\Documents\mws-restaurant-stage-1\node_modules\lws\lib\cli-app.js:11:34)
    at Function.run (C:\Users\bennyp\Documents\mws-restaurant-stage-1\node_modules\lws\lib\cli-app.js:23:21)
    at Object.<anonymous> (C:\Users\bennyp\Documents\mws-restaurant-stage-1\node_modules\local-web-server\bin\cli.js:12:29)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
(node:4020) ExperimentalWarning: The http2 module is an experimental API.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mws-restaurant-stage-1@1.0.0 start: `npx ws --verbose`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mws-restaurant-stage-1@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bennyp\AppData\Roaming\npm-cache\_logs\2018-03-04T19_17_08_815Z-debug.log
```

when disabling http2, all is good on windows.

This configuration works fine on macOS

**Comment by 75lb** [comment] 2018-03-04 19:29
i see, thanks for the report. I'll have a look at this ASAP.

The lws-http2 server plugin currently uses a fork of [node-http2](https://github.com/molnarg/node-http2), it needs updating to use the new http2 server built into node.

**Comment by bennypowers** [comment] 2018-03-04 19:42
Thanks! I appreciate your interest in this, as I'm hoping to use lws as part of a udacity nanodegree project (in place of the provided dev server 😉)

**Comment by bennypowers** [comment] 2018-03-04 23:01
FYI I got the same error when running in docker, starting from either node:carbon node:latest .

**Comment by 75lb** [comment] 2018-03-06 13:40
this is fixed in lws v1.1.8, it was not a windows-specific issue. Please re-install local-web-server to pick up the change.

It was caused by the fact `http2` recently became a node built-in module (adding native HTTP2 support to node). So passing `--server http2` loaded the built-in `http2` module instead of our third party `lws-http2` module.

In your `lws.config.js` you will now need to pass the full lws module name, to avoid confusion with the node built-in:

```
module.exports = {
  ...
  server: 'lws-http2',
  ...
};
```

**Closed by 75lb** 2018-03-06 13:40 UTC

**Comment by bennypowers** [comment] 2018-03-08 19:29
I got this crash while running http2 on mac

```
GET /bower_components/webcomponentsjs/webcomponents-loader.js 200 18.460 ms - -
internal/http2/compat.js:173
        const value = ref[prop];
                         ^

TypeError: Cannot read property 'removeListener' of undefined
    at Object.get (internal/http2/compat.js:173:26)
    at cleanup (/Users/bennyp/Documents/mws-restaurant-stage-1/node_modules/ee-first/index.js:62:12)
    at callback (/Users/bennyp/Documents/mws-restaurant-stage-1/node_modules/ee-first/index.js:54:5)
    at ServerHttp2Stream.onevent (/Users/bennyp/Documents/mws-restaurant-stage-1/node_modules/ee-first/index.js:93:5)
    at emitOne (events.js:121:20)
    at ServerHttp2Stream.emit (events.js:211:7)
    at emit (internal/http2/core.js:144:8)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mws-restaurant-stage-1@1.0.0 start: `npx ws`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mws-restaurant-stage-1@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bennyp/.npm/_logs/2018-03-08T19_28_29_979Z-debug.log
```

**Comment by 75lb** [comment] 2018-03-08 19:40
hmm, that line doesn't exist in the current node.js code - [see here](https://github.com/nodejs/node/blob/master/lib/internal/http2/compat.js#L173).

Please install the latest node (v9.7) and see if you get the same issue. I don't think this issue is lws-specific.

**Comment by bennypowers** [comment] 2018-03-08 19:57
Updated node and haven't gotten the error yet (was not consistently reproducible before)

Thanks for the heads up
