### ISSUE TITLE
Server has no output when executed by node exec()

### ISSUE THREAD

**Issue by brachkow** [lwsjs/local-web-server#162] opened 2021-07-02 01:22 UTC
When I run server from cli everything works as expected, but if I run it from node.js it doesn't output anything.

```javascript
const { exec } = require('child_process');
exec(
  `ws --directory ./dist/ --spa index.html --port 1111`,
  (error, stdout, stderr) => {
    if (error) {
      console.log(`error: ${error.message}`);
      return;
    }
    if (stderr) {
      console.log(`stderr: ${stderr}`);
      return;
    }
    console.log(`stdout: ${stdout}`);
  },
);
```

**Comment by 75lb** [comment] 2021-07-02 01:50
Use the API? 
https://github.com/lwsjs/local-web-server/wiki/API-reference

**Comment by brachkow** [comment] 2021-07-03 03:04
@75lb but I want to use in combination with other cli tools

**Comment by 75lb** [comment] 2021-07-03 09:47
`exec` does not return the output until the process has ended - the `ws` process never ends (until manually stopped) as it's a server, so by design it must stay alive.. 

To capture the output of a running process, use [spawn](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options). 

Closing, as this is not a bug with local-web-server.

**Closed by 75lb** 2021-07-03 09:47 UTC
