### ISSUE TITLE
--directory option/flag does not work with npx installs

### ISSUE THREAD

**Issue by iliandy** [lwsjs/local-web-server#136] opened 2019-10-30 20:05 UTC
--directory option/flag does not work with npx installs. However, it works with -g global installs.

**Comment by 75lb** [comment] 2019-11-03 11:08
I can't reproduce this, it works for me on macOS. This command hosts the `public` directory as expected. 

```
$ npx local-web-server --directory public
```

What OS are you on? Which versions of node and npm are installed? Could you paste the command that is failing please?

**Comment by 75lb** [comment] 2019-11-08 09:37
closing until I receive more info.

**Closed by 75lb** 2019-11-08 09:37 UTC
Labels: need more info

**Comment by Sytten** [comment] 2020-08-24 14:57
The config seems fine:
```
{
  port: 8000,
  moduleDir: [
    '.',
    '/Users/Sytten/Projects/MyProject/node_modules/local-web-server'
  ],
  modulePrefix: 'lws-',
  stack: MiddlewareStack [
    BasicAuth,      BodyParser,
    RequestMonitor, Log,
    Cors,           Json,
    Compress,       Rewrite,
    Blacklist,      ConditionalGet,
    Mime,           Range,
    SPA,            Static,
    Index
  ],
  directory: './build',
  spa: 'index.html',
  rewrite: [ '/app/(.*) -> /build/$1' ],
  view: CliView {}
}
```
So the problem is somewhere else, I will try to create a simple repo to show you the problem.

**Comment by 75lb** [comment] 2020-08-25 11:56
I installed yarn to test this myself, taking care to avoid using npm.. i created a test project with this structure: 

```
$ tree
.
├── package.json
├── public
   └── index.html
```

I ran this install command: 

```
$ yarn add local-web-server
```

This command worked as expected (hosting the `public` directory): 

```
$ ./node_modules/.bin/ws --directory public/
```

I added a `start` command to package.json:

```
{
  "name": "yarn-test",
  "author": "Lloyd Brookes <75pound@gmail.com>",
  "version": "0.0.0",
  "description": "yarn-test",
  "scripts": {
    "start": "ws --directory public"
  },
  "dependencies": {
    "local-web-server": "^4.2.1"
  }
}
```

This command also worked as expected (hosting the public dir): 

```
$ yarn start
```

I can't reproduce this issue. I will re-open the issue once I see it failing.
