### ISSUE TITLE
programatic url rewrite http->https not working correctly

### ISSUE THREAD

**Issue by dkebler** [lwsjs/local-web-server#76] opened 2017-10-31 01:13 UTC
Below is my code.  When I run this and type in the http request 

`trantor.645.kebler.net:8080`

the http server does not rewrite the url but it does serve the files from https server at the above url insecurely without https.

If I put in the https url all is well
`https://trantor.645.kebler.net:8443`

```
const LocalWebServer = require('local-web-server')
const https = new LocalWebServer()
const http = new LocalWebServer()

const CERT_PATH ='blah blah'
const CERT_NAME ='trantor.645.kebler.net'

const FILES_PATH ='blah blah'

http.listen({
  port: 8080,
  rewrite: '/* -> https://' + CERT_NAME + ':8443/$1'
})

https.listen({
  port: 8443,
  https: true,
  hostname: CERT_NAME,
  directory: FILES_PATH,
  spa: 'index.html',
  key: CERT_PATH + CERT_NAME + '.key',
  cert: CERT_PATH + CERT_NAME + '.crt'
})
```

**Comment by dkebler** [comment] 2017-10-31 02:08
Maybe what I was hoping for was a redirect like this which works fine as expected

```
const express = require('express');
const fs = require('fs');
const https = require('https');
const http = require('http');

let app = express();

http.createServer(app).listen(80);
https.createServer(app).listen(443);


app.use(function(req, res, next) {
    if (req.secure) {
      console.log(res)
        next();
    } else {
        res.redirect('https://' + req.headers.host + req.url);
    }
});
```

**Comment by 75lb** [comment] 2017-10-31 19:38
Hi, rewriting an incoming URL and returning a "302 Redirect" response are two completely different solutions to two different problems.

I'm not clear what the issue is, closing.

**Closed by 75lb** 2017-10-31 19:38 UTC

**Comment by dkebler** [comment] 2017-11-01 15:18
yes nothing wrong with rewrite.   this is not an issue but a feature request.  Support a redirect too.   Not a biggy.  Obviously I have a solution.

**Comment by 75lb** [comment] 2017-11-02 21:15
what is the feature you're requesting? Some way of achieving your redirect solution above with a simple command-line flag or option? How should it work, something like the below? 

```
$  ws --redirect-everything-to https://somewhere.else:9000
```

**Comment by bennypowers** [comment] 2018-02-24 21:01
Hi there, Thanks for the awesome package! I'm using it to develop PWAs locally.

[One of the Lighthouse criteria](https://developers.google.com/web/tools/lighthouse/audits/http-redirects-to-https) is that the site redirects requests from http to https. Of course, I can set up rewrite according to the wiki page's instructions, but that doesn't give me the 302 Redirect I need to pass this audit. 

I'd very much like some feature like `ws --server http2 --redirect-http-to-https` which will take all requests and redirect them to https.

Thanks for considering.
